### PR TITLE
adding pre-commit-config.yaml

### PR DESCRIPTION
**Pull request by alex-rakowski**
This pull request adds `pre-commit-config.yaml` file to  allow pre-commit to streamline code formatting and linting. Essientally it runs black and flake8 on commit for all staged files, and only allows commits if they both pass. This file doesn't affect behaviour unless developers choose to install and enable pre-commit for the repo. 

To use pre-commits you need to `pip install pre-commit`, run `pre-commit install` in the top level of the repo. It changes/creates the `.git/hooks/pre-commit`. It will then run every time you try to commit and only commit if they pass. You can call it manually with `pre-commit run`. 

You can bypass these checks and commit non-passing code by `git commit -m "Some message" --no-verify`

### CODE REVIEW

**Comment by bsavitzky** [comment]
Nice, thanks Alex! Been talking about adding this config with Matt, very
good idea :3

**Review by sezelt — APPROVED** [review]
I like this, it's a very good idea. 

We should probably put the instructions for how to install it and how to get around the checks somewhere more permanent than this PR conversation... perhaps in the developer guidelines doc @bsavitzky ?

**Comment by alex-rakowski** [comment]
@sezelt @bsavitzky. There's a [Contributors Guide gist](https://gist.github.com/bsavitzky/8b1ee4c1244814940e7cff4500535dba) on the `README.md.` I took a stab at creating a separate file `CONTRIBUTORS.md` that captures the pre-commit information, flake8, black, and general developer practices.  Feel free to edit it or I can revert this and keep it to just `pre-commit-config.yaml`.

**Review by sezelt — APPROVED** [review]
looks good to me

**Comment by bsavitzky** [comment]
Hey @alex-rakowski -

The pre-commit config is great.  Adding the contributor guidelines .md is also an important addition we've discussed, but should be a separate PR that we can review together without getting tangled up in this small .yaml config file.  

Can you remove the edits to the readme and the contributors .md files from this commit, and then open them as a new PR?

**Comment by alex-rakowski** [comment]
@bsavitzky it's now just back to `pre-commit-config.yaml`

**Review by bsavitzky — APPROVED** [review]

**Pull request merged**
