### PR TITLE
CI/CD - Adding installation checkers 

### PR DESCRIPTION
**Pull request by alex-rakowski**
This adds three different level of installation checks:
- quick makes sure any PR/Push to any branch, except main and dev, can be installed and imported on Python 3.10, on Ubuntu
- dev makes sure any PR/Push to dev can be installed and imported on python 3.9-3.11 on ubuntu
- main makes sure any PR/Push to main can be installed and imported  on python 3.9-3.11 on mac, ubuntu and windows, and checks but allows fail if it is compatible with 3.12

All have their ability to check against Apple silicon commented out to be ready when that image is available.

### CODE REVIEW

**Comment by alex-rakowski** [comment]
We should probably update the `pypi_upload.yml` to be dependent on these checks.

**Comment by bsavitzky** [comment]
These look great, thanks @alex-rakowski .  Let's wait until after the MM rush to review and accept these, they will be very helpful

**Comment by alex-rakowski** [comment]
Sounds good, I misread an issue on the slack channel and thought this solved a pre M&M need

**Comment by alex-rakowski** [comment]
Removed 3.9 checks

**Review by sezelt — APPROVED** [review]

**Pull request merged**
