### PR TITLE
numpy < 2

### PR DESCRIPTION
**Pull request by smribet**
Changing set-up file (for v 0.14 only) to avoid numpy 2 install errors

### CODE REVIEW

**Comment by mlhenderson** [comment]
@smribet Yes to numpy < 2.0.  Is the ncempy restriction also due to numpy?

**Review by mlhenderson — APPROVED** [review]

**Comment by smribet** [comment]
Yes I think I made a mistake specifying the version though. Should it be <= 1.11.2?

**Comment by mlhenderson** [comment]
<= 1.11.2 would be better, yes.  There are other changes for 1.11.2 besides the numpy restriction that should be picked up, which you would not get from 1.11.1.

**Review by mlhenderson — CHANGES_REQUESTED** [review]
we should also restrict pymatgen to < 2024.8.9, since that is pinned to numpy 2.0.0

**Comment by mlhenderson** [comment]
I did some local py4DSTEM testing using numpy 2, and emdfile has at least one incompatibility with numpy 2 currently.  It makes sense to put some version limits for py4DSTEM numpy install, at least temporarily, until the problems related to dependencies can be addressed.

**Comment by bsavitzky** [comment]
Thanks Matt - what incompatibility with emdfile did you find?

**Comment by mlhenderson** [comment]
I filed an issue with emdfile, so far one error related to usage of numpy.string_

https://github.com/py4dstem/emdfile/issues/2

**Comment by bsavitzky** [comment]
Great, thanks - fixed and pushed to a new branch `np2` for numpy 2
compatibility fixes.  Will leave the branch open for now while you're
testing

**Comment by smribet** [comment]
@bsavitzky it sounds like we should pin emdfile as well?

**Comment by bsavitzky** [comment]
Once we've ensured numpy 2 compatibility I'll merge and version emdfile.
Then we could simply bump the version dependency in py4DSTEM but leave the
>=. I think this is better than pinning in this situation but am curious -
do you think pinning would be preferable?

**Comment by smribet** [comment]
Sounds good!

**Review by bsavitzky — APPROVED** [review]

**Pull request merged**
