### PR TITLE
Celebrating the 38th day anniversary of 3.12 offical release 

### PR DESCRIPTION
**Pull request by alex-rakowski**
Quick Bump of python version and a couple workflows to allow 3.12.

### CODE REVIEW

**Comment by sezelt** [comment]
It looks like there are some new syntax checks in 3.12 that throw warnings when the package is imported:
```
Run python -c "import py4DSTEM; print(py4DSTEM.__version__)"
  python -c "import py4DSTEM; print(py4DSTEM.__version__)"
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.0/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.0/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.0/x64/lib
/home/runner/work/py4DSTEM/py4DSTEM/py4DSTEM/process/polar/polar_analysis.py:20: SyntaxWarning: invalid escape sequence '\i'
  """
/home/runner/work/py4DSTEM/py4DSTEM/py4DSTEM/process/polar/polar_analysis.py:231: SyntaxWarning: invalid escape sequence '\p'
  """
/home/runner/work/py4DSTEM/py4DSTEM/py4DSTEM/process/diffraction/crystal_viz.py:522: SyntaxWarning: invalid escape sequence '\.'
  warnings.filterwarnings("ignore", module="matplotlib\..*")
/home/runner/work/py4DSTEM/py4DSTEM/py4DSTEM/process/diffraction/crystal_viz.py:1707: SyntaxWarning: invalid escape sequence '\d'
  str(np.round(self.orientation_fiber_angles[0] * 0.00)) + "$\degree$",
/home/runner/work/py4DSTEM/py4DSTEM/py4DSTEM/process/diffraction/crystal_viz.py:1708: SyntaxWarning: invalid escape sequence '\d'
  str(np.round(self.orientation_fiber_angles[0] * 0.25)) + "$\degree$",
/home/runner/work/py4DSTEM/py4DSTEM/py4DSTEM/process/diffraction/crystal_viz.py:1709: SyntaxWarning: invalid escape sequence '\d'
  str(np.round(self.orientation_fiber_angles[0] * 0.50)) + "$\degree$",
/home/runner/work/py4DSTEM/py4DSTEM/py4DSTEM/process/diffraction/crystal_viz.py:1710: SyntaxWarning: invalid escape sequence '\d'
  str(np.round(self.orientation_fiber_angles[0] * 0.75)) + "$\degree$",
/home/runner/work/py4DSTEM/py4DSTEM/py4DSTEM/process/diffraction/crystal_viz.py:1711: SyntaxWarning: invalid escape sequence '\d'
  str(np.round(self.orientation_fiber_angles[0] * 1.00)) + "$\degree$",
0.14.9
```
These are indeed syntax errors so we should probably fix them! Either these need two `\` or they need to be raw strings.

**Comment by sezelt** [comment]
Other than that warning, I am not against allowing 3.12 but it looks like at the moment pymatgen does not support it, and that may lead to installation headaches.

**Comment by alex-rakowski** [comment]
I'll work on those syntax errors, it does show on the action but I guess it's configured for warnings to not fail. 

I checked the [setup.py](https://github.com/materialsproject/pymatgen/blob/master/setup.py#L29) which said >=3.9 But I was mainly relying on the actions to check as I thought we made it a dependency.

I just did an install of this branch with mp-api and pymatgen using 3.12 on my mac, and  it appears to work:

```
In [1]: from mp_api import client

In [2]: mpr = client.MPRester()
/Users/arakowski/miniconda3/envs/py312/lib/python3.12/site-packages/mp_api/client/mprester.py:227: UserWarning: mpcontribs-client not installed. Install the package to query MPContribs data, or construct pourbaix diagrams: 'pip install mpcontribs-client'
  warnings.warn(

In [3]: struct = mpr.get_structure_by_material_id('mp-4')
Retrieving MaterialsDoc documents: 100%|█████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12300.01it/s]

In [4]: struct
Out[4]:
Structure Summary
Lattice
    abc : 3.5948183736587107 3.59482031242994 3.59481981
 angles : 109.47121182807795 109.4712226521735 109.47122468172489
 volume : 35.7609782076631
      A : 3.38922722 -3e-08 -1.19827292
      B : -1.69461466 2.93515864 -1.19827292
      C : 1e-08 1e-08 3.59481981
    pbc : True True True
PeriodicSite: Nd (0.0, 0.0, 0.0) [-0.0, 0.0, 0.0]

In [5]: import py4DSTEM

In [6]: xtal = py4DSTEM.process.diffraction.Crystal.from_pymatgen_structure(struct)

In [7]: xtal
Out[7]: <py4DSTEM.process.diffraction.crystal.Crystal at 0x17ee4c800>
```

**Comment by sezelt** [comment]
OK, I think you may be right about pymatgen. I had tried making an environment with mamba and it failed with an error about pymatgen not being available, but nothing in their recipe seems to preclude 3.12 so it may have been a red herring.

**Comment by alex-rakowski** [comment]
I just checked their conda-forge, and there is no 3.12 label yet. Hopefully, their next update will, as I can't see anything in the feedstock that forbids 3.12 being created.

**Comment by bsavitzky** [comment]
Cool, I'm going to go ahead and merge - if we run into any issues we can always revist the setup.py

**Review by bsavitzky — APPROVED** [review]

**Pull request merged**
