### PR TITLE
Gui arrowkey

### PR DESCRIPTION
**Pull request by sezelt**
I showed Karen the GUI and she requested this feature... So here it is! (Also she thinks the GUI is awesome!)

Qt handles keyboard events in... interesting ways? So I ended up making a radio button for where you want control to go. Since once you attach keyboard events to the widget it really holds on to it, I have set it up so if you press anything other than an arrow key it leaves arrowkey mode. Otherwise even putting the cursor in other places wouldn't wrest control and people might get confused/angry...

### CODE REVIEW

**Comment by HamishGBrown** [comment]
This would be amazing, Good request 👍

**Comment by tcpekin** [comment]
This is absolutely my most used tool in the Matlab code I've written... this would be extremely nice. You could also see how hyperspy does it - their signal2D.plot() implementation is very nice as well, where it shows both a virtual DF and corresponding diffraction pattern, and you can either use arrow keys or click the VDF to move around.

**Comment by sezelt** [comment]
@tcpekin That's a good idea, hyperspy does handle this well. I just looked into how they do it, and I can't seem to get the same behavior to work in py4DSTEM. There's something I'm not understanding about how Qt dispatches key events and how to control it, so I end up either intercepting every keypress all of the time or none of them ever...

**Comment by tcpekin** [comment]
@sezelt I avoid Qt like the plague.. I'm happy you figured out at least how to intercept something.. Nice work.

**Pull request merged**
