### PR TITLE
reformat repo

### PR DESCRIPTION
**Pull request by smribet**
This PR reformats the repo. I think it will make it easier to compare and maintain code.

### CODE REVIEW

**Comment by alex-rakowski** [comment]
What style did you format with?

**Review by sezelt — APPROVED** [review]

**Comment by sezelt** [comment]
I am very much in favor of this change, and I think the overall sentiment at the dev meeting was in favor of this. @bsavitzky do you have any objections? If there are any spots where we really want some non-standard formatting we can mark it with `#fmt: off`/`#fmt: on`.

**Comment by alex-rakowski** [comment]
I'm also in favour. I think it would be worth adding a `.pre-commit-config.yaml`  to have black autoformat on each commit for developers

**Comment by sezelt** [comment]
#502 is a step in that direction, but just as a check and not something that will force changes

**Review by bsavitzky — APPROVED** [review]

**Comment by bsavitzky** [comment]
Sigh.  Ok!  Oh brave new world, with such uncompromising Python code formatters in it. [1][2]

@sezelt  I approved PR #502.  Unless you want to make additional edits, if you go ahead and un-draft it I/whoever can merge.

@alex-rakowski I don't want to have a .yaml action that modifies developer code just yet.  It is, of course, not unreasonable, and I think perhaps we'll get there.  For the moment, I'd prefer some stay on ceding control over minutiae of hand coding in favor of speed and determinism on fundamental grounds. [1]  Yes, PR#502 defacto does that.  Yes, this means you/we have to run black on our code ourselves.  By hand.  [laughs maniacally]

Let us continue discussion out in the world...

Anywho.  Merged!

[1] https://github.com/psf/black
[2] A Brave New World, Huxley

**Pull request merged**
