### PR TITLE
Adding PDF calculation function

### PR DESCRIPTION
**Pull request by cophus**
Both reduced and full PDFs added.  Tested against simulated data.  Still needs more work but basic functionality is there.

### CODE REVIEW

**Comment by bsavitzky** [comment]
Thanks Colin!  Starting a review now.

The first thing you'll want to do is pull from the dev branch (into your local version of this branch, then push to your remote fork you made the PR from) so that there aren't any merge conflicts in the PR.  Happy to help if you run into any issues with that.

**Comment by bsavitzky** [comment]
Also - could you attach some demo code with a (small) dataset that it runs on?  It will make reviewing this easier :)

**Comment by cophus** [comment]
Here are the notebooks I used for testing - an (incomplete) abTEM simulation for amorphous Ta, plus a quick and dirty pair distribution function calculation:
image
the PDF calculation notebook produces:
image

Data is here:
https://drive.google.com/file/d/1g2d_uSTyVWr8zITLuVdzMVUkIPnLAvmL/view?usp=sharing

[amor_Ta.zip](https://github.com/py4dstem/py4DSTEM/files/12478381/amor_Ta.zip)

**Comment by bsavitzky** [comment]
Hey @cophus - I've made a number of changes, including
- added documentation to all methods
- modified input args to remove unused values, tweaked names
- fixed return and plotting behaviors
- fixed a `.scattering_vectors` bug - in the future use `polardata.qq` instead
- fixed a bug where `.radial_var_norm` was assigned to `radial_var` rather than copied
- added storage of and independent plotting methods for the outputs of the final `calculate_pair_dist_function` method
- removed an extraneous call to `.scattering_model`

In the new doc strings for `.calculate_radial_statistics` and `.calculate_pair_dist_function` I've added specific descriptions of what these methods are computing.  When you get a chance, please
- [ ] review these equations for correctness, and
- [ ] add citations to the docstrings for these two methods where noted (`[@cophus TODO ADD CITATION]`)

**Comment by bsavitzky** [comment]
Attached is an updated version of the .ipynb that runs on the code following my commits!

Once you've had a chance to check out these changes and make that edit, let me know and I can complete the review :) 

[RDF01.ipynb.zip](https://github.com/py4dstem/py4DSTEM/files/12922606/RDF01.ipynb.zip)

**Comment by bsavitzky** [comment]
I'm merging this before the citations requested above have been added in order to have this module available in release code for a tutorial - the citations can get added in the next cycle...

**Pull request merged**
