### PR TITLE
BraggVects append fix

### PR DESCRIPTION
**Pull request by bsavitzky**
Fixes a bug in which saving in "appendover" mode failed for Custom type objects, like BraggVectors.

Note to devs! @smribet @sezelt @alex-rakowski @cophus @gvarnavi:
This PR bumps the `emdfile` version, which is required for good behavior.  *Most likely* this will not cause any issues in your dev environments after merging/pulling on this code, however, if it does, re-run `pip install -e .` to update emdfile.

### CODE REVIEW

**Comment by alex-rakowski** [comment]
@bsavitzky py4DSTEM should always be using the latest version of `emdfile` right? If so I think we could setup an action to update `setup.py` to the latest version of `emdfile` every time there's a push to `emdfile/main`

**Review by alex-rakowski — APPROVED** [review]

**Comment by bsavitzky** [comment]
Thanks for the suggestion @alex-rakowski - I think it's best to hold off on an action like that.  Each GH action requires maintenance, and is another fail point for an automation pipeline, and I think in a case like this automation really isn't needed.  Updating the version in setup.py was a trivial change/commit in a PR I had to make in to this repo anyway.  So I'd say its more complication than it's worth.

On the note of failure points in automation pipelines!  Something seems to have gone wrong with the read-the-docs build.  Remind me where we trigger a re-run of that process?  It's not with the other actions under Checks... :'''(

**Comment by alex-rakowski** [comment]
It looks like there was an issue with build the docs website. I just manually ran it there, and it built with no issues, so I think it's good to go.

**Comment by bsavitzky** [comment]
Cool, thanks Alex.

It'd be nice to be able to re-run this check the same way we re-run all the checks which are GH actions configured through .github/workflows/.yaml, but that has involved various hoops.  I modified the read-the-docs webhook so that it's supposed to run when you run workflows, instead of just on PR, but that didn't seem to do it.  Then the option to re-run the failed build through read-the-docs just apparently randomly appeared where I swear it wasn't this morning so that worked?  Maybe because of the webhook modification.....? That doesn't make sense to me, but, it worked! And now there are seven little green checkmarks and I am happy

**Pull request merged**
