### PR TITLE
Adding occupancy to py4DSTEM diffraction

### PR DESCRIPTION
**Pull request by cophus**
PR adds occupancy to crystal, plotting of structures, kinematical SF calcs.

Still needs to be done:
-add occupancy to dynamical SFs
-read occupancy from cif files

### CODE REVIEW

**Comment by cophus** [comment]
Comparing 2 structures with minor occupancy differences:

image (2)

image (1)

Notebook:  (unfinished)
[diffraction_05_occupancy.zip](https://github.com/py4dstem/py4DSTEM/files/13034432/diffraction_05_occupancy.zip)

**Comment by alex-rakowski** [comment]
Just to check so I can make sure I make #534 compatible, occupancy can either be None or 1D list or array with the same len as positions?

**Comment by sezelt** [comment]
Next steps:
- [ ] @sezelt add occupancy to dynamical structure factor calculations
- [ ] @sezelt add occupancy to pymatgen CIF reader
- [ ] @alex-rakowski add ASE importer to this PR

**Comment by alex-rakowski** [comment]
- changed `self.occupancy` to store as ones and updated the structure calcs to expect this. Crystal can still have None passed to init, and it will check that the occupancy and positions shapes match.
- added `from_prismatic` and `from_ase` loads from the objects and attempts to scrape the occupancy from the files

**Comment by sezelt** [comment]
I've added occupancy to the CIF reader and the structure factor calculations but I haven't tested it thoroughly

**Review by bsavitzky — APPROVED** [review]

**Pull request merged**
